services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  ghost:
    image: ghost:5-alpine
    container_name: ghost
    volumes:
      - ./ghost/theme/dist:/var/lib/ghost/content/themes/bitmunch:z
      # - ./ghost/config.production.json:/var/lib/ghost/config.production.json:z
      # - ./ghost/config.development.json:/var/lib/ghost/config.development.json:z #overwrite default settings 
    ports:
      - 8080:2368
    environment:
      # - NODE_ENV=production
      url: http://localhost:8080
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
    restart: always
    depends_on:
      - mysql

volumes:
  mysql:
